# Set platform to 13.0 for DJI iOS SDK compatibility
platform :ios, '13.0'

# Import the Flutter pod helper script dynamically
flutter_install_all_ios_pods_path = File.join('Flutter', 'podhelper.rb')
if File.exist?(flutter_install_all_ios_pods_path)
  require flutter_install_all_ios_pods_path
else
  flutter_root = nil
  generated_config_path = File.join('Flutter', 'Generated.xcconfig')
  if File.exist?(generated_config_path)
    File.foreach(generated_config_path) do |line|
      if line =~ /FLUTTER_ROOT=(.*)/
        flutter_root = $1.strip
      end
    end
  end
  if flutter_root
    require File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')
  else
    raise "Could not find podhelper.rb. Make sure you run 'flutter pub get' first."
  end
end

# CocoaPods analytics sends network stats. If you want to disable this, uncomment the following line.
# COCOAPODS_DISABLE_ANALYTICS = true

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # DJI iOS Mobile SDK Dependency
  pod 'DJI-SDK-iOS', '~> 4.16'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # DJI SDK requires bitcode to be turned off
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
