# Set platform to 13.0 for DJI iOS SDK compatibility
platform :ios, '13.0'

# CocoaPods analytics sends network stats. If you want to disable this, uncomment the following line.
# COCOAPODS_DISABLE_ANALYTICS = true

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.expand_path(File.join('..', 'Flutter'), __FILE__)
  
  # DJI iOS Mobile SDK Dependency
  pod 'DJI-SDK-iOS', '~> 4.16'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # DJI SDK requires bitcode to be turned off
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
